# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("DOG", "Dog"),
                            ("CAT", "Cat"),
                            ("EXOTIC", "Exotic"),
                            ("FARM", "Farm Animal"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("num_pets", models.PositiveIntegerField()),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_pet_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "calculated_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name_plural": "booking details",
                "db_table": "booking_details",
            },
        ),
    ]
