# Generated by Django 4.2.16 on 2025-01-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='pet_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Exotic', 'Exotic'), ('Farm', 'Farm Animal'), ('Other', 'Other')], max_length=50),
        ),
    ]
