# Generated by Django 4.2.16 on 2025-01-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0003_alter_bookingdetails_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='applies_after',
            field=models.PositiveIntegerField(default=1, help_text='Additional pet rate applies after this many pets'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='holiday_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='unit_of_time',
            field=models.CharField(choices=[('15_MIN', '15 minutes'), ('30_MIN', '30 minutes'), ('45_MIN', '45 minutes'), ('1_HOUR', '1 hour'), ('2_HOUR', '2 hours'), ('3_HOUR', '3 hours'), ('4_HOUR', '4 hours'), ('5_HOUR', '5 hours'), ('6_HOUR', '6 hours'), ('7_HOUR', '7 hours'), ('8_HOUR', '8 hours'), ('24_HOUR', '24 hours'), ('PER_DAY', 'Per day'), ('PER_VISIT', 'Per visit')], default='PER_VISIT', max_length=20),
        ),
    ]
