# Generated by Django 4.2.16 on 2025-01-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0004_bookingdetails_applies_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='unit_of_time',
        ),
    ]
