# Generated by Django 4.2.16 on 2025-01-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_occurrences', '0004_alter_bookingoccurrence_options_and_more'),
        ('booking_details', '0005_remove_bookingdetails_unit_of_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingdetails',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='booking_occurrence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='booking_occurrences.bookingoccurrence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='holiday_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='pet_type',
        ),
    ]
