# Generated by Django 4.2.19 on 2025-02-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0006_alter_bookingdetails_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='unit_of_time',
            field=models.CharField(default='Per Visit', max_length=20),
        ),
    ]
