# Generated by Django 4.2.19 on 2025-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0007_bookingdetails_unit_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='multiple',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=10),
        ),
    ]
