# Generated by Django 4.2.19 on 2025-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0008_bookingdetails_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='nights',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
