# Generated by Django 4.2.16 on 2024-11-23 00:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("DOG", "Dog"),
                            ("CAT", "Cat"),
                            ("BIRD", "Bird"),
                            ("FISH", "Fish"),
                            ("REPTILE", "Reptile"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                (
                    "pet_type",
                    models.CharField(
                        blank=True,
                        help_text="Specific type for exotic pets",
                        max_length=100,
                    ),
                ),
                (
                    "age_years",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "age_months",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="pet_photos/"),
                ),
                ("photo_gallery", models.JSONField(blank=True, default=list)),
                ("adoption_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pet_description", models.TextField(blank=True)),
                ("friendly_with_children", models.BooleanField(blank=True, null=True)),
                ("friendly_with_cats", models.BooleanField(blank=True, null=True)),
                ("friendly_with_dogs", models.BooleanField(blank=True, null=True)),
                ("spayed_neutered", models.BooleanField(blank=True, null=True)),
                ("house_trained", models.BooleanField(blank=True, null=True)),
                ("microchipped", models.BooleanField(blank=True, null=True)),
                ("feeding_schedule", models.TextField(blank=True)),
                ("potty_break_schedule", models.TextField(blank=True)),
                (
                    "energy_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_be_left_alone", models.BooleanField(blank=True, null=True)),
                ("medications", models.JSONField(blank=True, default=dict)),
                ("medication_notes", models.TextField(blank=True)),
                ("special_care_instructions", models.TextField(blank=True)),
                ("vet_name", models.CharField(blank=True, max_length=100)),
                ("vet_address", models.TextField(blank=True)),
                ("vet_phone", models.CharField(blank=True, max_length=20)),
                ("insurance_provider", models.CharField(blank=True, max_length=100)),
                ("vet_documents", models.JSONField(blank=True, default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
