# Generated by Django 4.2.16 on 2025-01-13 19:10

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="photo_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of paths to gallery photos",
                validators=[pets.models.validate_gallery_paths],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo for the pet. Maximum size: 5MB. Allowed formats: JPEG, PNG, GIF, WebP",
                null=True,
                upload_to=pets.models.pet_profile_photo_path,
                validators=[pets.models.validate_image_file],
            ),
        ),
    ]
