# Generated by Django 4.2.7 on 2025-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('N/A', 'N/A')], max_length=20),
        ),
    ]
