# Generated by Django 4.2.7 on 2025-06-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_fix_boolean_nulls'),
        ('pets', '0006_alter_pet_medications'),
        ('pets', 'fix_boolean_defaults'),
    ]

    operations = [
    ]
