# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingOccurrence",
            fields=[
                ("occurrence_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "calculated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("PROFESSIONAL", "Professional"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "last_modified_by",
                    models.CharField(
                        choices=[
                            ("CLIENT", "Client"),
                            ("PROFESSIONAL", "Professional"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINAL", "Final")], max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking_occurrences",
                "ordering": ["start_date", "start_time"],
            },
        ),
    ]
