# Generated by Django 4.2.16 on 2025-01-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_occurrences', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingoccurrence',
            name='calculated_cost',
        ),
    ]
