# Generated by Django 4.2.16 on 2025-01-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_occurrences', '0003_remove_bookingoccurrence_calculated_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoccurrence',
            options={'ordering': ['start_date', 'start_time'], 'verbose_name': 'Booking Occurrence', 'verbose_name_plural': 'Booking Occurrences'},
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
