# Generated by Django 4.2.19 on 2025-02-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_occurrences', '0005_add_calculated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='end_time',
            field=models.TimeField(help_text='Time in 24-hour format (UTC)'),
        ),
        migrations.AlterField(
            model_name='bookingoccurrence',
            name='start_time',
            field=models.TimeField(help_text='Time in 24-hour format (UTC)'),
        ),
    ]
