# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("service_moderation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemoderation",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions",
                to="services.service",
            ),
        ),
    ]
