# Generated by Django 4.2.7 on 2025-08-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0002_add_search_counter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('authenticated', 'Authenticated'), ('anonymous', 'Anonymous')], default='anonymous', max_length=20)),
                ('animal_types', models.JSONField(blank=True, default=list)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('service_query', models.CharField(blank=True, max_length=255, null=True)),
                ('overnight_service', models.BooleanField(blank=True, default=False, null=True)),
                ('price_range', models.JSONField(blank=True, default=dict)),
                ('radius_miles', models.IntegerField(blank=True, default=30, null=True)),
                ('filter_background_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('filter_insured', models.BooleanField(blank=True, default=False, null=True)),
                ('filter_elite_pro', models.BooleanField(blank=True, default=False, null=True)),
                ('results_found', models.IntegerField(blank=True, default=0, null=True)),
                ('has_fallback', models.BooleanField(blank=True, default=False, null=True)),
                ('search_successful', models.BooleanField(blank=True, default=False, null=True)),
                ('original_query_successful', models.BooleanField(blank=True, default=False, null=True)),
                ('search_query_summary', models.TextField(blank=True, null=True)),
                ('service_category', models.CharField(blank=True, max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('sort_method', models.CharField(blank=True, max_length=50)),
                ('result_count', models.IntegerField(blank=True, null=True)),
                ('results_clicked', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('search_count', models.IntegerField(default=1, help_text='Number of times this exact search has been performed')),
                ('first_searched', models.DateTimeField(default=django.utils.timezone.now, help_text='When this search combination was first performed')),
                ('last_searched', models.DateTimeField(default=django.utils.timezone.now, help_text='When this search combination was most recently performed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'search_logs_searchlog',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='getmatchedlog',
            index=models.Index(fields=['created_at'], name='get_matched_created_e72a52_idx'),
        ),
        migrations.AddIndex(
            model_name='getmatchedlog',
            index=models.Index(fields=['status'], name='get_matched_status_77c00b_idx'),
        ),
        migrations.AddIndex(
            model_name='getmatchedlog',
            index=models.Index(fields=['email'], name='get_matched_email_5ea35b_idx'),
        ),
        migrations.AddIndex(
            model_name='getmatchedlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='get_matched_ip_addr_3c9c40_idx'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['timestamp'], name='search_logs_timesta_ed5550_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['created_at'], name='search_logs_created_664b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', 'created_at'], name='search_logs_user_id_58b12d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='search_logs_ip_addr_5600cb_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['service_query'], name='search_logs_service_55eef5_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['location'], name='search_logs_locatio_913597_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_successful'], name='search_logs_search__a5c4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['search_count'], name='search_logs_search__88989d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['first_searched'], name='search_logs_first_s_e67b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['last_searched'], name='search_logs_last_se_148c16_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['ip_address', 'service_query', 'location'], name='search_logs_ip_addr_e3e416_idx'),
        ),
    ]
