# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("availability", "0002_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedAvailability",
            fields=[
                (
                    "shared_availability_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="availability.availability",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "shared availabilities",
                "db_table": "shared_availability",
                "unique_together": {("availability", "service")},
            },
        ),
    ]
