# Generated by Django 4.2.16 on 2025-01-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                ("search_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", models.JSONField()),
                ("service_category", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=100)),
                ("animal_types", models.JSONField()),
                ("price_range", models.JSONField()),
                ("duration", models.CharField(max_length=50)),
                ("sort_method", models.CharField(max_length=50)),
                ("result_count", models.IntegerField()),
                ("results_clicked", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
