# Generated by Django 4.2.16 on 2024-11-23 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = []
