# Generated by Django 4.2.16 on 2025-01-12 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial_clients_structure"),
        ("clients", "0003_update_client_model"),
    ]

    operations = []
