# Generated by Django 4.2.16 on 2025-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
