# Generated by Django 4.2.16 on 2025-01-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_client_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_sitter_payout',
        ),
    ]
