# Generated by Django 4.2.19 on 2025-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending initial Professional Changes', 'Pending Initial Professional Changes'), ('Pending Professional Changes', 'Pending Professional Changes'), ('Pending Client Approval', 'Pending Client Approval'), ('Confirmed Pending Professional Changes', 'Confirmed Pending Professional Changes'), ('Confirmed', 'Confirmed'), ('Denied', 'Denied'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Draft', 'Draft')], max_length=100),
        ),
    ]
