# Generated by Django 4.2.7 on 2025-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_agreed_tos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='pro_agreed_tos',
            field=models.BooleanField(default=False),
        ),
    ]
