# Generated by Django 4.2.7 on 2025-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_client_agreed_tos_booking_pro_agreed_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes_from_pro',
            field=models.TextField(blank=True, help_text='Notes from the professional to the client for this booking', null=True),
        ),
    ]
