# Generated by Django 4.2.16 on 2024-11-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="approved_cat_sitting",
            new_name="approved_for_cats",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="approved_dog_sitting",
            new_name="approved_for_dogs",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="approved_exotics_sitting",
            new_name="approved_for_exotics",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="date_joined",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="wants_cat_sitting_approval",
            new_name="wants_cat_approval",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="wants_dog_sitting_approval",
            new_name="wants_dog_approval",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="wants_exotics_sitting_approval",
            new_name="wants_exotics_approval",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
