# Generated by Django 4.2.16 on 2025-01-13 19:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_date_joined_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for the user. Maximum size: 5MB. Allowed formats: JPEG, PNG, GIF, WebP",
                null=True,
                upload_to=users.models.user_profile_photo_path,
                validators=[users.models.validate_image_file],
            ),
        ),
    ]
