# Generated by Django 4.2.19 on 2025-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Waitlister',
                'verbose_name_plural': 'Waitlisters',
                'db_table': 'waitlisters',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_waitlister',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='signed_up_on_beta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.IntegerField(default=0, help_text='0: Free tier, 1: Waitlist tier, 2: Commission tier, 3: Pro subscription, 4: Client subscription, 5: Dual subscription'),
        ),
    ]
