# Generated by Django 4.2.19 on 2025-04-05 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_waitlister_user_is_waitlister_user_signed_up_on_beta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_time_logging_in', models.BooleanField(default=True)),
                ('first_time_logging_in_after_signup', models.BooleanField(default=True)),
                ('done_pro_profile_tutorial', models.BooleanField(default=False)),
                ('done_client_profile_tutorial', models.BooleanField(default=False)),
                ('done_client_dashboard_tutorial', models.BooleanField(default=False)),
                ('done_pets_preferences_tutorial', models.BooleanField(default=False)),
                ('done_settings_payments_tutorial', models.BooleanField(default=False)),
                ('done_search_pros_tutorial', models.BooleanField(default=False)),
                ('done_become_pro_tutorial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tutorial statuses',
                'db_table': 'tutorial_status',
            },
        ),
    ]
