# Generated by Django 4.2.19 on 2025-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tutorialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialstatus',
            name='done_client_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorialstatus',
            name='done_pro_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
