# Generated by Django 4.2.19 on 2025-04-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tutorialstatus_done_client_tutorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_become_pro_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_client_dashboard_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_client_profile_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_pets_preferences_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_pro_profile_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_search_pros_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='done_settings_payments_tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='first_time_logging_in',
        ),
        migrations.RemoveField(
            model_name='tutorialstatus',
            name='first_time_logging_in_after_signup',
        ),
    ]
