# Generated by Django 4.2.19 on 2025-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_tutorialstatus_done_become_pro_tutorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
