# Generated by Django 4.2.19 on 2025-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usersettings_marketing_communications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_visible',
            field=models.BooleanField(default=True),
        ),
    ]
