# Generated by Django 4.2.7 on 2025-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('google', 'Google'), ('friend', 'Friend'), ('reddit', 'Reddit'), ('nextdoor', 'Nextdoor'), ('other', 'Other')], help_text='How the user heard about CrittrCove', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='how_did_you_hear_other',
            field=models.CharField(blank=True, help_text="Custom text when 'other' is selected for how_did_you_hear", max_length=255, null=True),
        ),
    ]
