# Generated by Django 4.2.7 on 2025-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_how_did_you_hear_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('google', 'Google'), ('reddit', 'Reddit'), ('nextdoor', 'Nextdoor'), ('other', 'Other')], help_text='How the user heard about CrittrCove', max_length=50, null=True),
        ),
    ]
