# Generated by Django 4.2.7 on 2025-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_friend_from_how_did_you_hear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted Privacy Policy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_version',
            field=models.CharField(blank=True, help_text='Version of Privacy Policy accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted Terms of Service', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of Terms of Service accepted', max_length=20),
        ),
    ]
