# Generated by Django 4.2.7 on 2025-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_tos_privacy_policy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_policy_accepted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privacy_version',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_accepted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_version',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_and_privacy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted both Terms of Service and Privacy Policy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_and_privacy_version',
            field=models.CharField(blank=True, help_text='Version of Terms of Service and Privacy Policy accepted', max_length=20),
        ),
    ]
