# Generated by Django 4.2.7 on 2025-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_combine_tos_privacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When account was actually deleted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_confirmation_token',
            field=models.CharField(blank=True, help_text='Token for confirming account deletion via email', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When user requested account deletion', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the deletion confirmation token expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='True if account has been soft deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deletion_requested',
            field=models.BooleanField(default=False, help_text='True if user has requested account deletion'),
        ),
    ]
