# Generated by Django 4.2.7 on 2025-08-17 22:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_account_deletion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[users.models.validate_phone_number]),
        ),
    ]
