# Generated by Django 4.2.7 on 2025-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
