# Generated by Django 4.2.16 on 2025-02-08 03:48

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_authorized_household_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='authorized_household_members',
            field=models.JSONField(blank=True, default=clients.models.default_list, help_text='List of people authorized to interact with the pet'),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=clients.models.default_dict, help_text='List of emergency contacts'),
        ),
    ]
