# Generated by Django 4.2.7 on 2025-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_add_invited_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='marked_noreply_as_not_spam',
            field=models.BooleanField(default=False, help_text='True if client has marked noreply@zenexotics.com as not spam'),
        ),
    ]
