# Generated by Django 4.2.16 on 2025-01-13 23:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("DOG", "Dog"),
                            ("CAT", "Cat"),
                            ("EXOTIC", "Exotic"),
                            ("FARM", "Farm Animal"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        size=None,
                    ),
                ),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_animal_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("holiday_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_of_time",
                    models.CharField(
                        choices=[
                            ("15_MIN", "15 Minutes"),
                            ("30_MIN", "30 Minutes"),
                            ("1_HOUR", "1 Hour"),
                            ("DAY", "Day"),
                            ("WEEK", "Week"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("moderation_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("searchable", models.BooleanField(default=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["-created_at"],
            },
        ),
    ]
