# Generated by Django 4.2.16 on 2025-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_of_time',
            field=models.CharField(choices=[('15 Min', '15 Min'), ('30 Min', '30 Min'), ('45 Min', '45 Min'), ('1 Hour', '1 Hour'), ('2 Hour', '2 Hour'), ('3 Hour', '3 Hour'), ('4 Hour', '4 Hour'), ('5 Hour', '5 Hour'), ('6 Hour', '6 Hour'), ('7 Hour', '7 Hour'), ('8 Hour', '8 Hour'), ('24 Hour', '24 Hour'), ('Per Day', 'Per Day'), ('Per Visit', 'Per Visit'), ('Week', 'Week')], max_length=50),
        ),
    ]
