# Generated by Django 4.2.16 on 2025-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_of_time',
            field=models.CharField(choices=[('15_MIN', '15 Minutes'), ('30_MIN', '30 Minutes'), ('45_MIN', '45 Minutes'), ('1_HOUR', '1 Hour'), ('2_HOUR', '2 Hours'), ('3_HOUR', '3 Hours'), ('4_HOUR', '4 Hours'), ('5_HOUR', '5 Hours'), ('6_HOUR', '6 Hours'), ('7_HOUR', '7 Hours'), ('8_HOUR', '8 Hours'), ('24_HOUR', '24 Hours'), ('PER_DAY', 'Per Day'), ('PER_VISIT', 'Per Visit'), ('WEEK', 'Week')], max_length=50),
        ),
    ]
