# Generated by Django 4.2.19 on 2025-02-23 21:06

from django.db import migrations

def convert_time_unit_case(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    
    # Define the mapping of old values to new values
    time_unit_mapping = {
        'PER_DAY': 'Per Day',
        'PER_VISIT': 'Per Visit',
        'per_day': 'Per Day',
        'per_visit': 'Per Visit',
        'per day': 'Per Day',
        'per visit': 'Per Visit',
    }
    
    # Update all services that have incorrect casing
    for service in Service.objects.all():
        if service.unit_of_time in time_unit_mapping:
            service.unit_of_time = time_unit_mapping[service.unit_of_time]
            service.save()

def reverse_convert_time_unit_case(apps, schema_editor):
    # No need to reverse this migration as it's just fixing casing
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_applies_after'),
    ]

    operations = [
        migrations.RunPython(convert_time_unit_case, reverse_convert_time_unit_case),
    ]
