# Generated by Django 4.2.19 on 2025-03-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_convert_time_unit_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='Indicates if this service requires overnight stay'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_of_time',
            field=models.CharField(choices=[('15 Min', '15 Min'), ('30 Min', '30 Min'), ('45 Min', '45 Min'), ('1 Hour', '1 Hour'), ('2 Hour', '2 Hour'), ('3 Hour', '3 Hour'), ('4 Hour', '4 Hour'), ('5 Hour', '5 Hour'), ('6 Hour', '6 Hour'), ('7 Hour', '7 Hour'), ('8 Hour', '8 Hour'), ('24 Hour', '24 Hour'), ('Per Day', 'Per Day'), ('Per Night', 'Per Night'), ('Per Visit', 'Per Visit'), ('Week', 'Week')], max_length=50),
        ),
    ]
