# Generated by Django 4.2.19 on 2025-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_overnight_alter_service_unit_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this service is active'),
        ),
    ]
