# Generated by Django 4.2.19 on 2025-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='animal_type',
            field=models.CharField(max_length=50),
        ),
    ]
