# Generated by Django 4.2.19 on 2025-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='holiday_rate_is_percent',
            field=models.BooleanField(default=True, help_text='Indicates if holiday rate is a percentage or fixed amount'),
        ),
    ]
