# Generated by Django 4.2.19 on 2025-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_holiday_rate_is_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.AddField(
            model_name='service',
            name='animal_types',
            field=models.JSONField(default=dict, help_text='JSON field mapping animal types to their categories'),
        ),
    ]
