# Generated by Django 4.2.19 on 2025-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_service_animal_type_remove_service_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=50),
        ),
    ]
