# Generated by Django 4.2.7 on 2025-07-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indicates if this service has been archived due to past bookings'),
        ),
    ]
