# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingPets",
            fields=[
                ("bookingspet_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name_plural": "booking pets",
                "db_table": "booking_pets",
            },
        ),
    ]
