# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking_pets", "0001_initial"),
        ("bookings", "0001_initial"),
        ("pets", "0002_alter_pet_photo_gallery_alter_pet_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpets",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_pets",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingpets",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookingpets",
            unique_together={("booking", "pet")},
        ),
    ]
