# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingOccurrenceRate",
            fields=[
                (
                    "occurrence_rate_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("rate_title", models.CharField(max_length=255)),
                ("rate_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "booking_occurrence_rates",
                "ordering": ["created_at"],
            },
        ),
    ]
