# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking_occurrences", "0001_initial"),
        ("booking_occurrence_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingoccurrencerate",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="booking_occurrences.bookingoccurrence",
            ),
        ),
    ]
