# Generated by Django 4.2.16 on 2025-01-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_occurrences', '0003_remove_bookingoccurrence_calculated_cost'),
        ('booking_occurrence_rates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoccurrencerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingoccurrencerate',
            name='rate_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bookingoccurrencerate',
            unique_together={('occurrence', 'rate_title')},
        ),
        migrations.AlterModelTable(
            name='bookingoccurrencerate',
            table='booking_occurrence_rates_v2',
        ),
    ]
