# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingDraft",
            fields=[
                ("draft_id", models.AutoField(primary_key=True, serialize=False)),
                ("draft_data", models.JSONField()),
                (
                    "last_modified_by",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Professional"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("FINALIZED", "Finalized"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking_drafts",
                "ordering": ["-updated_at"],
            },
        ),
    ]
