# Generated by Django 4.2.16 on 2025-01-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_drafts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdraft',
            name='original_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
