# Generated by Django 4.2.19 on 2025-03-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_subtotal_and_more'),
        ('booking_drafts', '0003_bookingdraft_original_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdraft',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='bookings.booking'),
        ),
    ]
