# Generated by Django 4.2.16 on 2025-01-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalFacility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('available_for', models.CharField(choices=[('Dogs', 'Dogs'), ('Cats', 'Cats'), ('Exotics', 'Exotics'), ('All', 'All')], max_length=10)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='professionals.professional')),
            ],
            options={
                'db_table': 'professional_facilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
