# Generated by Django 4.2.16 on 2025-02-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_remove_usermessage_is_booking_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='type_of_message',
            field=models.CharField(choices=[('initial_booking_request', 'Initial Booking Request'), ('normal_message', 'Normal Message'), ('approval_request', 'Approval Request'), ('request_changes', 'Request Changes'), ('send_approved_message', 'Send Approved Message')], default='normal_message', max_length=30),
        ),
    ]
