# Generated by Django 4.2.19 on 2025-04-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_add_message_metrics'),
        ('user_messages', '0003_alter_usermessage_type_of_message'),
    ]

    operations = [
    ]
