# Generated by Django 4.2.19 on 2025-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_merge_20250421_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='type_of_message',
            field=models.CharField(choices=[('initial_booking_request', 'Initial Booking Request'), ('normal_message', 'Normal Message'), ('approval_request', 'Approval Request'), ('request_changes', 'Request Changes'), ('send_approved_message', 'Send Approved Message'), ('booking_confirmed', 'Booking Confirmed')], default='normal_message', max_length=30),
        ),
    ]
