# Generated by Django 4.2.7 on 2025-06-09 03:03

from django.db import migrations, models
import user_messages.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0005_alter_usermessage_type_of_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image attachment for the message. Maximum size: 5MB. Allowed formats: JPEG, PNG, GIF, WebP', null=True, upload_to=user_messages.helpers.message_image_path, validators=[user_messages.helpers.validate_message_image]),
        ),
    ]
