# Generated by Django 4.2.7 on 2025-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0006_usermessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='type_of_message',
            field=models.CharField(choices=[('initial_booking_request', 'Initial Booking Request'), ('normal_message', 'Normal Message'), ('approval_request', 'Approval Request'), ('request_changes', 'Request Changes'), ('send_approved_message', 'Send Approved Message'), ('booking_confirmed', 'Booking Confirmed'), ('image_message', 'Image Message')], default='normal_message', max_length=30),
        ),
    ]
