# Generated by Django 4.2.7 on 2025-08-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0007_alter_usermessage_type_of_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_sender_deleted',
            field=models.BooleanField(default=False, help_text='True if the sender has been deleted'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender_name_backup',
            field=models.CharField(blank=True, help_text='Backup of sender name for deleted users', max_length=255),
        ),
    ]
