# Generated by Django 4.2.19 on 2025-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='total_num_of_reviews',
        ),
        migrations.AddField(
            model_name='professional',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
