# Generated by Django 4.2.19 on 2025-03-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_remove_professional_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Professional', 'verbose_name_plural': 'Professionals'},
        ),
        migrations.RemoveField(
            model_name='professional',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='insurance_expiry_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='stripe_account_id',
        ),
    ]
