# Generated by Django 4.2.7 on 2025-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_alter_professional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_background_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professional',
            name='is_elite_pro',
            field=models.BooleanField(default=False),
        ),
    ]
