# Generated by Django 4.2.7 on 2025-08-15 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVisitorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('colorado_springs_visitors', models.PositiveIntegerField(default=0)),
                ('colorado_visitors', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(default=dict, help_text='Top visited blog pages')),
                ('cities_breakdown', models.JSONField(default=dict, help_text='Visitor breakdown by city')),
                ('states_breakdown', models.JSONField(default=dict, help_text='Visitor breakdown by state')),
                ('top_referrers', models.JSONField(default=dict, help_text='Top referrer sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Visitor Summary',
                'verbose_name_plural': 'Blog Visitor Summaries',
                'db_table': 'blog_visitor_summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BlogVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('page', models.CharField(help_text='Blog page visited', max_length=255)),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, help_text='Hashed IP for privacy', max_length=64)),
                ('session_hash', models.CharField(blank=True, help_text='Hashed session identifier', max_length=64)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_colorado_springs', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tracking data')),
            ],
            options={
                'verbose_name': 'Blog Visitor',
                'verbose_name_plural': 'Blog Visitors',
                'db_table': 'blog_visitors',
                'indexes': [models.Index(fields=['visited_at'], name='blog_visito_visited_b5b701_idx'), models.Index(fields=['page'], name='blog_visito_page_b0098f_idx'), models.Index(fields=['is_colorado_springs'], name='blog_visito_is_colo_787f3a_idx'), models.Index(fields=['ip_hash'], name='blog_visito_ip_hash_e04ac2_idx'), models.Index(fields=['session_hash'], name='blog_visito_session_43f4f2_idx')],
            },
        ),
    ]
