# Generated by Django 4.2.7 on 2025-08-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogVisitorSummary',
        ),
        migrations.AlterField(
            model_name='blogvisitor',
            name='page',
            field=models.CharField(help_text='Blog page visited (includes query params)', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogvisitor',
            name='referrer',
            field=models.URLField(blank=True, help_text='External referrer URL', null=True),
        ),
    ]
