# Generated by Django 4.2.7 on 2025-06-13 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0003_alter_professional_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_alter_booking_status'),
        ('clients', '0006_add_invited_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('moderation_reason', models.TextField(blank=True, null=True)),
                ('review_visible', models.BooleanField(default=False)),
                ('review_posted', models.BooleanField(default=False)),
                ('post_deadline', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='clients.client')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_moderated', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Professional Review',
                'verbose_name_plural': 'Professional Reviews',
                'db_table': 'reviews_professional_reviews',
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('moderation_reason', models.TextField(blank=True, null=True)),
                ('review_visible', models.BooleanField(default=False)),
                ('review_posted', models.BooleanField(default=False)),
                ('post_deadline', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='bookings.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='clients.client')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_moderated', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'db_table': 'reviews_client_reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('CLIENT', 'Client Review'), ('PROFESSIONAL', 'Professional Review')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_requests',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'user', 'review_type')},
            },
        ),
    ]
