# Generated by Django 4.2.7 on 2025-06-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_type', models.CharField(choices=[('client', 'Client'), ('professional', 'Professional')], max_length=20)),
                ('reviewee_type', models.CharField(choices=[('client', 'Client'), ('professional', 'Professional')], max_length=20)),
                ('reviewer_id', models.IntegerField()),
                ('reviewee_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='reviews_rev_booking_3929ad_idx'), models.Index(fields=['reviewer_id'], name='reviews_rev_reviewe_e817a5_idx'), models.Index(fields=['reviewee_id'], name='reviews_rev_reviewe_57bac6_idx')],
                'unique_together': {('booking', 'reviewer_type', 'reviewee_type')},
            },
        ),
    ]
