# Generated by Django 4.2.7 on 2025-06-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=50),
        ),
    ]
