class UnitOfTime:
    FIFTEEN_MINUTES = '15 Min'
    THIRTY_MINUTES = '30 Min'
    FORTY_FIVE_MINUTES = '45 Min'
    ONE_HOUR = '1 Hour'
    TWO_HOURS = '2 Hour'
    THREE_HOURS = '3 Hour'
    FOUR_HOURS = '4 Hour'
    FIVE_HOURS = '5 Hour'
    SIX_HOURS = '6 Hour'
    SEVEN_HOURS = '7 Hour'
    EIGHT_HOURS = '8 Hour'
    TWENTY_FOUR_HOURS = '24 Hour'
    PER_DAY = 'Per Day'
    PER_VISIT = 'Per Visit'
    WEEK = 'Week'