# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingSummary",
            fields=[
                ("summary_id", models.AutoField(primary_key=True, serialize=False)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("client_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxes", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_client_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_sitter_payout",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fee_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tax_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name_plural": "booking summaries",
                "db_table": "booking_summary",
            },
        ),
    ]
