# Generated by Django 4.2.16 on 2025-01-25 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_summary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsummary',
            name='client_fee',
        ),
        migrations.RemoveField(
            model_name='bookingsummary',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='bookingsummary',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='bookingsummary',
            name='total_client_cost',
        ),
        migrations.RemoveField(
            model_name='bookingsummary',
            name='total_sitter_payout',
        ),
        migrations.AddField(
            model_name='bookingsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
