# Generated by Django 4.2.16 on 2025-01-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_subtotal_and_more'),
        ('booking_summary', '0003_remove_bookingsummary_client_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsummary',
            options={'verbose_name': 'Booking Summary', 'verbose_name_plural': 'Booking Summaries'},
        ),
        migrations.AlterField(
            model_name='bookingsummary',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='bookingsummary',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage (e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookingsummary',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Tax percentage (e.g., 8.00 for 8%)', max_digits=5),
        ),
    ]
