# Generated by Django 4.2.19 on 2025-02-17 22:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_summary', '0004_alter_bookingsummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsummary',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
