# Generated by Django 4.2.16 on 2025-01-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("error_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("error_message", models.TextField()),
                ("metadata", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="error_logs__timesta_fce9bb_idx"
                    ),
                    models.Index(
                        fields=["endpoint"], name="error_logs__endpoin_237e7f_idx"
                    ),
                ],
            },
        ),
    ]
