# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("availability", "0001_initial"),
        ("professionals", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="professionals.professional",
            ),
        ),
    ]
