# Generated by Django 4.2.16 on 2025-01-25 22:30

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_occurrences', '0003_remove_bookingoccurrence_calculated_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOccurrenceRate',
            fields=[
                ('occurrence_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rates', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of rates with title, description, and amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='booking_occurrences.bookingoccurrence')),
            ],
            options={
                'verbose_name': 'Booking Occurrence Rate',
                'verbose_name_plural': 'Booking Occurrence Rates',
                'db_table': 'booking_occurrence_rates',
            },
        ),
    ]
