# Generated by Django 4.2.16 on 2025-01-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "payment_method_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("BANK_ACCOUNT", "Bank Account"),
                        ],
                        max_length=50,
                    ),
                ),
                ("stripe_payment_method_id", models.CharField(max_length=255)),
                ("last4", models.CharField(max_length=4)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "bank_account_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_methods",
                "ordering": ["-created_at"],
            },
        ),
    ]
