# Generated by Django 4.2.16 on 2025-01-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type_of_payment',
            field=models.CharField(choices=[('Pay_for', 'Pay For'), ('Receive_payment', 'Receive Payment'), ('both', 'Both')], default='Pay_for', help_text='Determines if this payment method can be used for paying, receiving payments, or both', max_length=50),
        ),
    ]
