# Generated by Django 4.2.7 on 2025-08-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_paymentmethod_type_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='type_of_payment',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_primary_payment',
            field=models.BooleanField(default=False, help_text='Whether this is the primary method for making payments'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_primary_payout',
            field=models.BooleanField(default=False, help_text='Whether this is the primary method for receiving payouts'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('user', 'stripe_payment_method_id'), name='unique_user_stripe_payment_method'),
        ),
    ]
